Repository Redot-Engine/redot-engine, pull requests merged in 2024-12, with the labels that each got.

#882 Fix Twitter link in readme
  README.md
Labels: bug, documentation

#898 [4.3] Merge commit godotengine/godot@63e0fb5
  platform/android/doc_classes/EditorExportPlatformAndroid.xml
  platform/android/export/export_plugin.cpp
  platform/android/export/export_plugin.h
  platform/android/java/lib/res/mipmap-anydpi-v26/icon.xml
  platform/android/java/lib/res/mipmap-anydpi-v26/themed_icon.xml
  platform/android/java/lib/res/mipmap/icon_monochrome.png
  scene/resources/canvas_item_material.cpp
  scene/resources/material.cpp
  scene/resources/particle_process_material.cpp
Labels: merge:godot

#900 [4.3] Add donation button back
  editor/editor_node.cpp
Labels: enhancement, topic:editor, cherrypick:master

#901 Add donation button back
  editor/editor_node.cpp
Labels: enhancement, topic:editor

#903 [4.3] Add Redot codespell documentation correction
  .pre-commit-config.yaml
  custom_dict.txt
  doc/classes/EditorPaths.xml
  doc/classes/FileAccess.xml
  doc/classes/OS.xml
  doc/classes/ProjectSettings.xml
  doc/classes/RenderingDevice.xml
  modules/csg/doc_classes/CSGShape3D.xml
  modules/enet/doc_classes/ENetConnection.xml
  modules/gltf/doc_classes/GLTFCamera.xml
  modules/gltf/doc_classes/GLTFDocument.xml
  modules/gltf/doc_classes/GLTFDocumentExtension.xml
  modules/gltf/doc_classes/GLTFLight.xml
  modules/gltf/doc_classes/GLTFPhysicsBody.xml
  modules/gltf/doc_classes/GLTFPhysicsShape.xml
  modules/gltf/doc_classes/GLTFSkeleton.xml
  modules/gltf/doc_classes/GLTFState.xml
  modules/gridmap/doc_classes/GridMap.xml
  modules/mono/doc_classes/CSharpScript.xml
  modules/multiplayer/doc_classes/SceneMultiplayer.xml
  modules/openxr/doc_classes/OpenXRActionMap.xml
  modules/openxr/doc_classes/OpenXRCompositionLayer.xml
  modules/openxr/doc_classes/OpenXRInterface.xml
  modules/text_server_adv/doc_classes/TextServerAdvanced.xml
  modules/text_server_fb/doc_classes/TextServerFallback.xml
  modules/theora/doc_classes/VideoStreamTheora.xml
  platform/ios/doc_classes/EditorExportPlatformIOS.xml
  platform/web/doc_classes/EditorExportPlatformWeb.xml
Labels: bug, enhancement, documentation, cherrypick:master

#905 [4.3] Improve rebrand codespell regex structure
  .pre-commit-config.yaml
  custom_dict.txt
  doc/classes/RDShaderSource.xml
  doc/classes/RenderingDevice.xml
  doc/classes/ResourceImporter.xml
  doc/classes/SoftBody3D.xml
  modules/gltf/doc_classes/GLTFPhysicsBody.xml
  modules/gltf/doc_classes/GLTFPhysicsShape.xml
  modules/openxr/doc_classes/OpenXRActionMap.xml
  modules/regex/doc_classes/RegEx.xml
  modules/text_server_adv/doc_classes/TextServerAdvanced.xml
  modules/text_server_fb/doc_classes/TextServerFallback.xml
  modules/upnp/doc_classes/UPNP.xml
Labels: bug, rebranding, documentation

#904 Add Redot codespell documentation correction
  .pre-commit-config.yaml
  custom_dict.txt
  doc/classes/EditorPaths.xml
  doc/classes/EditorScript.xml
  doc/classes/Engine.xml
  doc/classes/OS.xml
  doc/classes/PCKPacker.xml
  doc/classes/ProjectSettings.xml
  doc/classes/RenderingDevice.xml
  doc/classes/ResourceImporter.xml
  doc/classes/ShaderIncludeDB.xml
  doc/classes/SoftBody3D.xml
  modules/csg/doc_classes/CSGShape3D.xml
  modules/enet/doc_classes/ENetConnection.xml
  modules/gltf/doc_classes/GLTFCamera.xml
  modules/gltf/doc_classes/GLTFDocument.xml
  modules/gltf/doc_classes/GLTFDocumentExtension.xml
  modules/gltf/doc_classes/GLTFLight.xml
  modules/gltf/doc_classes/GLTFNode.xml
  modules/gltf/doc_classes/GLTFObjectModelProperty.xml
  modules/gltf/doc_classes/GLTFPhysicsBody.xml
  modules/gltf/doc_classes/GLTFPhysicsShape.xml
  modules/gltf/doc_classes/GLTFSkeleton.xml
  modules/gltf/doc_classes/GLTFState.xml
  modules/gridmap/doc_classes/GridMap.xml
  modules/mono/doc_classes/CSharpScript.xml
  modules/multiplayer/doc_classes/SceneMultiplayer.xml
  modules/openxr/doc_classes/OpenXRActionMap.xml
  modules/openxr/doc_classes/OpenXRCompositionLayer.xml
  modules/openxr/doc_classes/OpenXRInterface.xml
  modules/regex/doc_classes/RegEx.xml
  modules/text_server_adv/doc_classes/TextServerAdvanced.xml
  modules/text_server_fb/doc_classes/TextServerFallback.xml
  modules/theora/doc_classes/VideoStreamTheora.xml
  modules/upnp/doc_classes/UPNP.xml
  platform/ios/doc_classes/EditorExportPlatformIOS.xml
  platform/web/doc_classes/EditorExportPlatformWeb.xml
Labels: bug, enhancement, rebranding, documentation

#908 [4.3] Added get_open_scenes_roots to Editor Interface API
  doc/classes/EditorInterface.xml
  editor/editor_interface.cpp
  editor/editor_interface.h
Labels: enhancement, topic:editor, tracked:godot, cherrypick:master
