Repository Redot-Engine/redot-engine, pull requests merged in 2024-11, with the labels that each got.

#832 [4.3] Fix templates treating official releases as dev releases
  editor/export/export_template_manager.cpp
  version.py
Labels: bug, cherrypick:master

#831 Fix remainder of godotengine references
  editor/doc_tools.cpp
  editor/editor_help.cpp
  editor/editor_node.cpp
  editor/editor_property_name_processor.cpp
  editor/fbx_importer_manager.cpp
  platform/linuxbsd/wayland/display_server_wayland.cpp
Labels: bug, rebranding, topic:network

#828 [4.3] Cherry-picks for the 4.3 branch - 1st batch
  core/math/basis.h
  doc/classes/BackBufferCopy.xml
  doc/classes/EditorDebuggerPlugin.xml
  doc/classes/EditorDebuggerSession.xml
  doc/classes/EditorSettings.xml
  doc/classes/EngineDebugger.xml
  doc/classes/FileDialog.xml
  doc/classes/HTTPRequest.xml
  doc/classes/Node.xml
  doc/classes/ProjectSettings.xml
  doc/classes/String.xml
  doc/classes/Transform2D.xml
  editor/debugger/script_editor_debugger.cpp
  editor/editor_file_system.cpp
  editor/editor_settings.cpp
  editor/plugins/canvas_item_editor_plugin.cpp
  editor/progress_dialog.cpp
  editor/progress_dialog.h
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/TestData/Sources/MustBeVariant.GD0301.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/MustBeVariantAnalyzer.cs
  modules/mono/glue/GodotSharp/GodotSharp/Core/Dictionary.cs
  modules/mono/glue/GodotSharp/GodotSharp/Core/Extensions/GodotObjectExtensions.cs
  modules/mono/glue/GodotSharp/GodotSharp/Core/Transform2D.cs
  modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs
  platform/android/java/editor/src/main/AndroidManifest.xml
  platform/android/java/editor/src/main/java/org/godotengine/editor/EditorMessageDispatcher.kt
  platform/android/java/editor/src/main/java/org/godotengine/editor/EditorWindowInfo.kt
  platform/android/java/editor/src/main/java/org/godotengine/editor/GodotEditor.kt
  platform/android/java/editor/src/main/java/org/godotengine/editor/GodotGame.kt
  platform/android/java/editor/src/main/res/drawable/ic_play_window_foreground.xml
  platform/android/java/editor/src/main/res/drawable/outline_fullscreen_exit_48.xml
  platform/android/java/editor/src/main/res/drawable/pip_button_activated_bg_drawable.xml
  platform/android/java/editor/src/main/res/drawable/pip_button_bg_drawable.xml
  platform/android/java/editor/src/main/res/drawable/pip_button_default_bg_drawable.xml
  platform/android/java/editor/src/main/res/layout/godot_game_layout.xml
  platform/android/java/editor/src/main/res/mipmap-anydpi-v26/ic_play_window.xml
  platform/android/java/editor/src/main/res/mipmap-hdpi/ic_play_window.png
  platform/android/java/editor/src/main/res/mipmap-mdpi/ic_play_window.png
  platform/android/java/editor/src/main/res/mipmap-xhdpi/ic_play_window.png
  platform/android/java/editor/src/main/res/mipmap-xxhdpi/ic_play_window.png
  platform/android/java/editor/src/main/res/mipmap-xxxhdpi/ic_play_window.png
  platform/android/java/editor/src/main/res/values/dimens.xml
  platform/android/java/editor/src/main/res/values/strings.xml
  platform/android/java/lib/src/org/godotengine/godot/GodotActivity.kt
  platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java
  platform/android/java/lib/src/org/godotengine/godot/utils/ProcessPhoenix.java
  scene/main/viewport.cpp
  scene/main/viewport.h
  thirdparty/README.md
  thirdparty/ufbx/ufbx.c
  thirdparty/ufbx/ufbx.h
Labels: bug, enhancement, platform:android, topic:core, topic:buildsystem, topic:editor, topic:porting, documentation, topic:thirdparty, topic:dotnet, topic:import, topic:2d, topic:export, performance

#773 Optimize `Node.find_children`
  scene/main/node.cpp
Labels: enhancement, topic:core, performance

#835 [4.3] Fix ignoring status_version for updating
  editor/engine_update_label.cpp
Labels: bug, topic:network, cherrypick:master

#837 Fix godot references in the issue & PR template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: rebranding

#842 [4.3] Merge commit godotengine/godot@33c02a5
  thirdparty/README.md
  thirdparty/certs/ca-certificates.crt
Labels: merge:godot

#846 [4.3] Change Godot Linux appdata urls to Redot
  misc/dist/linux/org.redotengine.Redot.appdata.xml
Labels: bug, rebranding, platform:linuxbsd, topic:buildsystem, cherrypick:master

#847 [4.3] Add support for redotengine.org template mirror automation
  editor/export/export_template_manager.cpp
Labels: enhancement, topic:editor, topic:network, cherrypick:master

#848 [4.3] Fix `VERSION_FULL_CONFIG` excess dot on 0
  core/version.h
Labels: bug, topic:core, cherrypick:master

#851 [4.3] Replace `versions.json` check with Github release check
  editor/engine_update_label.cpp
  editor/engine_update_label.h
Labels: enhancement, topic:editor, topic:network, cherrypick:master

#852 [4.3] Fix `gh_ratelimit`'s creation path being outside Redot
  editor/engine_update_label.cpp
Labels: bug, topic:editor, cherrypick:master

#856 [4.3] Fix Redot being logged as godot in android logger
  platform/android/os_android.cpp
Labels: bug, rebranding, platform:android, topic:core

#860 [4.3] Fix android logger Godot references to Redot
  platform/android/java/lib/src/org/godotengine/godot/GodotDownloaderAlarmReceiver.java
  platform/android/java/lib/src/org/godotengine/godot/GodotDownloaderService.java
  platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java
Labels: bug, rebranding, platform:android, cherrypick:master

#862 [4.3] Rebrand godette into redot-chan on platformer 2 comment for consistency
  platform/web/api/web_tools_editor_plugin.cpp
Labels: rebranding

#863 [4.3] Merge commit godotengine/godot@711c725
  core/io/resource.cpp
  core/io/resource_loader.cpp
  core/io/resource_loader.h
  core/object/class_db.cpp
  core/object/worker_thread_pool.cpp
  core/object/worker_thread_pool.h
  core/os/condition_variable.h
  core/os/mutex.h
  core/os/safe_binary_mutex.h
  core/templates/command_queue_mt.cpp
  core/templates/command_queue_mt.h
  editor/animation_track_editor.cpp
  editor/editor_resource_preview.cpp
  modules/gdscript/gdscript_cache.cpp
  modules/gdscript/gdscript_cache.h
  platform/windows/os_windows.cpp
  platform/windows/os_windows.h
  scene/register_scene_types.cpp
Labels: merge:godot

#865 [4.3] Correct `Node._unhandled_picking_input` to refer to InputEvent
  doc/classes/Node.xml
Labels: bug, documentation, cherrypick:master

#866 [4.3] Optimize `String::replace` methods
  core/string/ustring.cpp
Labels: bug, enhancement, topic:core, crash, performance

#868 [4.3] Fix 32-bit Windows build
  platform/windows/os_windows.cpp
Labels: bug, platform:windows, topic:buildsystem

#875 Merge commit godotengine/godot@9e60984
  core/config/project_settings.cpp
  core/extension/gdextension.cpp
  core/input/input_event.cpp
  core/input/input_event.h
  core/input/input_map.cpp
  core/input/input_map.h
  core/io/resource_loader.cpp
  doc/classes/EditorSpinSlider.xml
  doc/classes/FileAccess.xml
  drivers/vulkan/rendering_device_driver_vulkan.cpp
  editor/animation_track_editor.cpp
  editor/animation_track_editor.h
  editor/event_listener_line_edit.cpp
  editor/export/project_export.cpp
  editor/gui/editor_spin_slider.cpp
  editor/input_event_configuration_dialog.cpp
  editor/plugins/lightmap_gi_editor_plugin.cpp
  modules/gridmap/editor/grid_map_editor_plugin.cpp
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/ExportDiagnosticsTests.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/ScriptPropertiesGeneratorTests.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/TestData/GeneratedSources/ExportDiagnostics_GD0108_ScriptProperties.generated.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/TestData/GeneratedSources/ExportDiagnostics_GD0109_ScriptProperties.generated.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/TestData/GeneratedSources/ExportDiagnostics_GD0110_ScriptProperties.generated.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/TestData/GeneratedSources/ExportedToolButtons_ScriptProperties.generated.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/TestData/Sources/ExportDiagnostics_GD0108.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/TestData/Sources/ExportDiagnostics_GD0109.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/TestData/Sources/ExportDiagnostics_GD0110.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators.Tests/TestData/Sources/ExportedToolButtons.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/AnalyzerReleases.Unshipped.md
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/Common.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ExtensionMethods.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/GodotClasses.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/GodotEnums.cs
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ScriptPropertiesGenerator.cs
  modules/mono/glue/GodotSharp/GodotSharp/Core/Attributes/ExportToolButtonAttribute.cs
  modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj
  modules/multiplayer/multiplayer_spawner.cpp
  modules/multiplayer/multiplayer_spawner.h
  platform/android/export/export_plugin.cpp
  platform/android/export/gradle_export_util.cpp
  scene/3d/mesh_instance_3d.cpp
  scene/gui/spin_box.cpp
  scene/gui/spin_box.h
  scene/main/viewport.cpp
  servers/rendering/renderer_rd/environment/sky.cpp
  servers/rendering/renderer_rd/environment/sky.h
  servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp
  servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp
  servers/rendering/renderer_rd/shaders/environment/sky.glsl
  servers/rendering/rendering_device.cpp
  servers/rendering/rendering_device_graph.cpp
  servers/rendering/rendering_device_graph.h
  tests/scene/test_fontfile.h
  tests/test_main.cpp
Labels: merge:godot

#876 [4.3] Revert "ResourceLoader: Report error if resource type unrecognized"
  core/io/resource_loader.cpp
Labels: bug, topic:core, regression

#879 [4.3] Fix invalid doc references to godot_notifications
  doc/classes/Object.xml
  doc/classes/SceneTree.xml
Labels: bug, rebranding, documentation, cherrypick:master

#887 [4.3] Corrected manpage
  misc/dist/linux/redot.6
Labels: bug, rebranding, cherrypick:master
