Repository Redot-Engine/redot-engine, pull requests merged in 2024-10, with the labels that each got.

#261 fix: uses the exposed Redot global instead of the no longer existing Godot
  platform/web/SCsub
  platform/web/eslint.config.cjs
  platform/web/js/engine/config.js
  platform/web/js/engine/engine.externs.js
  platform/web/js/engine/engine.js
Labels: bug, good first issue

#649 Updated the logo for project manager
  editor/icons/TitleBarLogo.svg
Labels: Rebranding

#648 Deref Godot: misc/
  editor/debugger/debug_adapter/debug_adapter_parser.cpp
  editor/editor_file_system.cpp
  editor/editor_settings.cpp
  editor/export/editor_export_platform.cpp
  editor/export/export_template_manager.cpp
  editor/filesystem_dock.cpp
  editor/gui/editor_file_dialog.cpp
  editor/icons/README.md
  editor/import/3d/resource_importer_scene.cpp
  editor/plugins/asset_library_editor_plugin.cpp
  editor/plugins/node_3d_editor_plugin.cpp
  editor/project_converter_3_to_4.cpp
  editor/project_manager.cpp
  editor/run_instances_dialog.cpp
  editor/themes/editor_color_map.h
  editor/themes/editor_icons.cpp
  main/main.cpp
  main/steam_tracker.h
  misc/dist/html/editor.html
  misc/dist/html/service-worker.js
  misc/dist/ios_xcode/godot_ios.xcodeproj/project.pbxproj
  misc/dist/linux/godot.6
  misc/dist/shell/_godot.zsh-completion
  misc/dist/shell/godot.fish
  misc/dist/windows/README.md
  misc/dist/windows/godot.iss
  misc/scripts/check_ci_log.py
  misc/scripts/copyright_headers.py
  misc/scripts/header_guards.py
  misc/scripts/install_d3d12_sdk_windows.py
  misc/scripts/install_vulkan_sdk_macos.sh
  misc/utility/godot_gdb_pretty_print.py
Labels: Rebranding

#656 Fix Project Manager listing incorrect info
  COPYRIGHT.txt
  REDOT_AUTHORS.md
  core/SCsub
  core/config/engine.cpp
  core/config/engine.h
  core/core_bind.cpp
  core/core_bind.h
  core/core_builders.py
  core/version.h
  doc/classes/Engine.xml
  editor/editor_about.cpp
  methods.py
  version.py
Labels: bug

#660 Renable CHANGED_FILES for static_checks.yml
  .github/workflows/static_checks.yml
Labels: bug

#662 Fixed TitleBarLogo not rendering text
  editor/icons/TitleBarLogo.svg
Labels: bug

#676 Fix release.yml causing failing CI
  .github/workflows/release.yml
Labels: bug

#699 [4.3] Renable CHANGED_FILES for static_checks.yml
  .github/workflows/static_checks.yml
Labels: bug

#701 Merge commit godotengine@92e51fc
  .github/CODEOWNERS
  .github/workflows/windows_builds.yml
  core/config/project_settings.cpp
  core/math/geometry_2d.cpp
  doc/classes/Environment.xml
  doc/classes/PackedVector2Array.xml
  drivers/d3d12/SCsub
  drivers/d3d12/dxil_hash.cpp
  drivers/d3d12/rendering_device_driver_d3d12.cpp
  drivers/egl/egl_manager.cpp
  drivers/egl/egl_manager.h
  drivers/gles3/rasterizer_gles3.cpp
  drivers/gles3/rasterizer_gles3.h
  drivers/gles3/rasterizer_scene_gles3.cpp
  drivers/gles3/shaders/scene.glsl
  drivers/gles3/storage/material_storage.cpp
  drivers/gles3/storage/mesh_storage.cpp
  drivers/gles3/storage/mesh_storage.h
  drivers/metal/rendering_device_driver_metal.mm
  editor/animation_track_editor.cpp
  editor/editor_paths.cpp
  editor/editor_settings.cpp
  editor/export/export_template_manager.cpp
  editor/multi_node_edit.cpp
  editor/plugins/editor_preview_plugins.cpp
  editor/plugins/font_config_plugin.cpp
  editor/project_manager/project_dialog.cpp
  modules/bcdec/image_decompress_bcdec.cpp
  modules/gdscript/gdscript_analyzer.cpp
  modules/gdscript/gdscript_editor.cpp
  modules/gdscript/tests/scripts/.editorconfig
  modules/mono/editor/bindings_generator.cpp
  modules/mono/editor/bindings_generator.h
  modules/mono/glue/GodotSharp/GodotSharp/Core/Dictionary.cs
  modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/Marshaling.cs
  modules/noise/doc_classes/FastNoiseLite.xml
  platform/windows/detect.py
  scene/2d/skeleton_2d.cpp
  scene/2d/skeleton_2d.h
  scene/3d/node_3d.cpp
  scene/3d/skeleton_3d.cpp
  scene/3d/skeleton_3d.h
  scene/resources/material.cpp
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp
  servers/rendering/renderer_rd/storage_rd/mesh_storage.h
  servers/rendering/shader_compiler.cpp
  servers/rendering/shader_language.cpp
Labels: enhancement

#710 [4.3] Fix CI static checks indenting
  .github/workflows/static_checks.yml
Labels: bug, topic:buildsystem

#707 Recolor icon.svg to fit project rebranding
  editor/icons/DefaultProjectIcon.svg
Labels: enhancement

#682 Add status_version to versioning
  core/SCsub
  core/config/engine.cpp
  doc/classes/Engine.xml
  methods.py
  version.py
Labels: enhancement, topic:buildsystem

#709 [4.3] Fix websocket dropping messages for WSLPeer
  modules/websocket/packet_buffer.h
  modules/websocket/wsl_peer.cpp
  modules/websocket/wsl_peer.h
Labels: bug, topic:network

#730 [4.3] Remove `(Official)` from asset library button
  editor/plugins/asset_library_editor_plugin.cpp
Labels: bug, rebranding

#729 [4.4] Updated CONTRIBUTING.md w/ PR Guideline and Redot Docs links
  CONTRIBUTING.md
Labels: bug, rebranding, documentation

#731 Remove CI jobs that do not match Godot
  .github/workflows/linux_builds.yml
  .github/workflows/windows_builds.yml
Labels: bug, topic:buildsystem

#733 [4.3] Updated CONTRIBUTING.md w/ PR Guideline and Redot Docs links
  CONTRIBUTING.md
Labels: bug, rebranding, documentation

#735 Rebranding: Doc/
  doc/classes/@GlobalScope.xml
  doc/classes/AStar3D.xml
  doc/classes/CameraServer.xml
  doc/classes/Color.xml
  doc/classes/CompressedCubemap.xml
  doc/classes/CompressedCubemapArray.xml
  doc/classes/CompressedTexture2D.xml
  doc/classes/CompressedTexture2DArray.xml
  doc/classes/CompressedTexture3D.xml
  doc/classes/ConfigFile.xml
  doc/classes/Control.xml
  doc/classes/Dictionary.xml
  doc/classes/DisplayServer.xml
  doc/classes/EditorExportPlatform.xml
  doc/classes/EditorExportPlugin.xml
  doc/classes/EditorImportPlugin.xml
  doc/classes/EditorSettings.xml
  doc/classes/Engine.xml
  doc/classes/FileAccess.xml
  doc/classes/Image.xml
  doc/classes/InputEventMIDI.xml
  doc/classes/JSON.xml
  doc/classes/MainLoop.xml
  doc/classes/Node.xml
  doc/classes/Node2D.xml
  doc/classes/OS.xml
  doc/classes/PackedByteArray.xml
  doc/classes/PhysicsServer2DExtension.xml
  doc/classes/PhysicsServer3D.xml
  doc/classes/ProjectSettings.xml
  doc/classes/RDPipelineColorBlendStateAttachment.xml
  doc/classes/RDPipelineDepthStencilState.xml
  doc/classes/RDShaderFile.xml
  doc/classes/RDShaderSPIRV.xml
  doc/classes/RDShaderSource.xml
  doc/classes/RandomNumberGenerator.xml
  doc/classes/TextureButton.xml
  doc/classes/TextureProgressBar.xml
  doc/classes/Variant.xml
  doc/classes/Vector2.xml
  doc/classes/Vector3.xml
  doc/classes/VehicleWheel3D.xml
  doc/classes/VideoStreamPlayer.xml
  doc/classes/VisualShaderNodeComment.xml
  doc/classes/VisualShaderNodeFloatFunc.xml
  doc/classes/VisualShaderNodeFloatOp.xml
  doc/classes/VisualShaderNodeInput.xml
  doc/classes/XRInterface.xml
  doc/translations/de.po
  doc/translations/es.po
  doc/translations/fr.po
  misc/dist/linux/godot.6
  misc/dist/linux/org.godotengine.Godot.appdata.xml
Labels: bug, rebranding

#746 [4.3] Calculate pixel snap in canvas space instead of world space
  drivers/gles3/shaders/canvas.glsl
  servers/rendering/renderer_rd/shaders/canvas.glsl
Labels: bug, topic:rendering, topic:2d, tracked:godot

#745 [4.3] Rebranding: Doc/
  doc/classes/@GlobalScope.xml
  doc/classes/AStar3D.xml
  doc/classes/CameraServer.xml
  doc/classes/Color.xml
  doc/classes/CompressedCubemap.xml
  doc/classes/CompressedCubemapArray.xml
  doc/classes/CompressedTexture2D.xml
  doc/classes/CompressedTexture2DArray.xml
  doc/classes/CompressedTexture3D.xml
  doc/classes/ConfigFile.xml
  doc/classes/Control.xml
  doc/classes/Dictionary.xml
  doc/classes/DisplayServer.xml
  doc/classes/EditorExportPlatform.xml
  doc/classes/EditorExportPlugin.xml
  doc/classes/EditorSettings.xml
  doc/classes/Engine.xml
  doc/classes/Image.xml
  doc/classes/InputEventMIDI.xml
  doc/classes/JSON.xml
  doc/classes/MainLoop.xml
  doc/classes/Node.xml
  doc/classes/Node2D.xml
  doc/classes/OS.xml
  doc/classes/PackedByteArray.xml
  doc/classes/PhysicsServer2DExtension.xml
  doc/classes/PhysicsServer3D.xml
  doc/classes/ProjectSettings.xml
  doc/classes/RDPipelineColorBlendStateAttachment.xml
  doc/classes/RDPipelineDepthStencilState.xml
  doc/classes/RDShaderFile.xml
  doc/classes/RDShaderSPIRV.xml
  doc/classes/RandomNumberGenerator.xml
  doc/classes/TextureButton.xml
  doc/classes/TextureProgressBar.xml
  doc/classes/Variant.xml
  doc/classes/Vector2.xml
  doc/classes/Vector3.xml
  doc/classes/VehicleWheel3D.xml
  doc/classes/VideoStreamPlayer.xml
  doc/classes/VisualShaderNodeComment.xml
  doc/classes/XRInterface.xml
  doc/translations/de.po
  doc/translations/es.po
  doc/translations/fr.po
  misc/dist/linux/godot.6
  misc/dist/linux/org.godotengine.Godot.appdata.xml
Labels: bug, rebranding, documentation

#747 [4.3] Add an additional input stage after physics picking
  doc/classes/Node.xml
  scene/main/node.cpp
  scene/main/node.h
  scene/main/scene_tree.cpp
  scene/main/scene_tree.h
  scene/main/viewport.cpp
  scene/main/viewport.h
  tests/scene/test_node.h
Labels: enhancement, topic:input, tracked:godot

#754 [4.3] Condense two copyright sections by same author into one
  COPYRIGHT.txt
Labels: bug, rebranding

#753 [4.3] Add status_version to versioning
  core/SCsub
  core/config/engine.cpp
  doc/classes/Engine.xml
  methods.py
  version.py
Labels: enhancement, topic:core, topic:buildsystem

#751 Add maximum traversals to AStarGrid2D
  core/math/a_star_grid_2d.cpp
  core/math/a_star_grid_2d.h
  doc/classes/AStarGrid2D.xml
Labels: enhancement, topic:navigation

#749 Update logo license and copyright file
  COPYRIGHT.txt
  LOGO_LICENSE.txt
Labels: bug, rebranding

#759 Merge commit godotengine/godot@80f0b33
  core/string/translation_domain.cpp
  doc/classes/FileAccess.xml
  doc/classes/FileDialog.xml
  doc/classes/ProjectSettings.xml
  doc/classes/RenderingServer.xml
  doc/classes/Viewport.xml
  drivers/d3d12/rendering_device_driver_d3d12.cpp
  drivers/vulkan/rendering_device_driver_vulkan.cpp
  editor/animation_bezier_editor.cpp
  editor/animation_track_editor.cpp
  editor/debugger/editor_debugger_tree.cpp
  editor/debugger/editor_visual_profiler.cpp
  editor/editor_node.cpp
  editor/export/editor_export_platform.cpp
  editor/gui/editor_file_dialog.cpp
  editor/gui/editor_object_selector.cpp
  editor/import/dynamic_font_import_settings.cpp
  editor/plugins/animation_player_editor_plugin.cpp
  editor/plugins/editor_plugin.cpp
  editor/plugins/sprite_frames_editor_plugin.cpp
  modules/gdscript/gdscript.cpp
  modules/navigation/nav_map.cpp
  platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java
  platform/linuxbsd/wayland/display_server_wayland.cpp
  platform/macos/doc_classes/EditorExportPlatformMacOS.xml
  platform/macos/export/export_plugin.cpp
  scene/3d/mesh_instance_3d.cpp
  scene/3d/skeleton_3d.cpp
  scene/debugger/scene_debugger.cpp
  scene/gui/item_list.cpp
  scene/gui/menu_bar.cpp
  servers/rendering/renderer_canvas_cull.cpp
  servers/rendering/renderer_rd/shaders/forward_mobile/scene_forward_mobile.glsl
  servers/rendering/rendering_device.cpp
  servers/rendering/rendering_device.h
  servers/rendering/rendering_device_driver.cpp
  servers/rendering/rendering_device_driver.h
Labels: merge:godot

#756 Fixed the visual studio project creation for debugging
  methods.py
  misc/msvs/props.template
  misc/msvs/vcxproj.template
Labels: bug, rebranding, topic:buildsystem

#762 Update Logo Font and Enhance Visibility (Brandkit 1.1)
  editor/icons/TitleBarLogo.svg
  icon.png
  icon.svg
  icon_outlined.png
  icon_outlined.svg
  logo.png
  logo.svg
  logo_outlined.png
  logo_outlined.svg
  main/app_icon.png
  main/splash.png
Labels: bug, rebranding

#765 [4.3] Update Logo Font and Enhance Visibility (Brandkit 1.1)
  editor/icons/TitleBarLogo.svg
  icon.png
  icon.svg
  icon_outlined.png
  icon_outlined.svg
  logo.png
  logo.svg
  logo_outlined.png
  logo_outlined.svg
  main/app_icon.png
  main/splash.png
Labels: bug, rebranding

#766 Fix solution build failure when using Visual Studio IDE
  platform/windows/detect.py
Labels: bug, topic:buildsystem

#770 [4.3] Fix `Projection::invert` on orthogonal projections and others.
  core/math/projection.cpp
  tests/core/math/test_projection.h
  tests/test_main.cpp
Labels: bug, topic:core

#768 Rebrand extension API validation
  misc/scripts/validate_extension_api.sh
Labels: enhancement, rebranding, topic:gdextension

#775 [4.3] Rebrand macos exports to Redot
  platform/macos/export/export_plugin.cpp
Labels: bug, rebranding, platform:macos, topic:export

#786 [4.3] Rebrand Godot macos dist icons to Redot
  misc/dist/macos_template.app/Contents/Resources/icon.icns
  misc/dist/macos_tools.app/Contents/Resources/Godot.icns
Labels: bug, rebranding, platform:macos, cherrypick:master

#785 [4.3] Fix mono SDK references temporarily
  modules/mono/build_scripts/build_assemblies.py
  modules/mono/editor/Godot.NET.Sdk/Godot.NET.Sdk/Godot.NET.Sdk.csproj
  modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/Godot.SourceGenerators.csproj
  modules/mono/editor/GodotTools/GodotTools.IdeMessaging/GodotTools.IdeMessaging.csproj
  modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj
  modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj
Labels: bug, rebranding, topic:buildsystem, topic:dotnet

#774 Rebrand macos exports to Redot
  platform/macos/export/export_plugin.cpp
Labels: bug, rebranding, platform:macos, topic:export, cherrypick:4.3

#726 Add One Pixel Snap Button to the Tile Data Editor
  editor/icons/SnapHalf.svg
  editor/icons/SnapOne.svg
  editor/plugins/tiles/tile_data_editors.cpp
  editor/plugins/tiles/tile_data_editors.h
Labels: enhancement, topic:editor, cherrypick:4.3

#790 Rename Godot.icns to Redot.icns
  misc/dist/macos_tools.app/Contents/Resources/Redot.icns
Labels: bug, rebranding, platform:macos, cherrypick:master

#791 [4.3] Fix VERSION_FULL_CONFIG ignoring status versioning
  core/config/engine.cpp
  core/version.h
  methods.py
Labels: bug, rebranding, topic:buildsystem, cherrypick:master

#793 [4.3] Fix `EngineUpdateLabel` referring to godotengine.org
  editor/engine_update_label.cpp
Labels: bug, rebranding, topic:editor, topic:network, cherrypick:master

#800 Fix build versioning to account for status_version
  methods.py
Labels: bug, topic:buildsystem, cherrypick:master

#787 Cherry-picks for the master (4.4) branch - 1st batch
  core/config/engine.cpp
  core/version.h
  doc/classes/Node.xml
  editor/engine_update_label.cpp
  methods.py
  misc/dist/macos_template.app/Contents/Resources/icon.icns
  misc/dist/macos_tools.app/Contents/Resources/Godot.icns
  misc/dist/macos_tools.app/Contents/Resources/Redot.icns
  scene/main/node.cpp
  scene/main/node.h
  scene/main/scene_tree.cpp
  scene/main/scene_tree.h
  scene/main/viewport.cpp
  scene/main/viewport.h
  tests/scene/test_node.h
Labels: bug, enhancement, rebranding, platform:macos, topic:buildsystem, topic:editor, topic:network, topic:input

#796 Expose `ColorPicker.old_color` as a property
  doc/classes/ColorPicker.xml
  scene/gui/color_picker.cpp
Labels: enhancement, topic:gui

#783 [4.3] Unify `ColorPicker` color mode slider colors
  scene/gui/color_mode.cpp
  scene/gui/color_mode.h
Labels: bug, topic:gui, cherrypick:master

#782 [4.3] Remove `ColorModeOKHSL.get_shape_override`
  scene/gui/color_mode.h
Labels: enhancement, topic:gui, cherrypick:master

#779 [4.3] Remove superfluous `ColorPicker` Containers
  scene/gui/color_picker.cpp
Labels: bug, topic:gui, cherrypick:master

#803 [4.3] Fix `ColorPicker` overbright indicator position
  scene/gui/color_picker.cpp
Labels: bug, topic:gui, cherrypick:master

#781 [4.3] Unify `ColorPicker` HSV Rectangle/Wheel draw
  scene/gui/color_picker.cpp
Labels: enhancement, topic:gui, cherrypick:master

#784 [4.3] Remove hide on `ColorPicker` color picking
  scene/gui/color_picker.cpp
Labels: enhancement, topic:gui, cherrypick:master

#794 [4.3] Fix RGB/RAW `ColorMode` jank sliders and spinbox
  scene/gui/color_mode.cpp
  scene/gui/color_mode.h
Labels: enhancement, topic:gui, cherrypick:master

#769 Fix `Projection::invert` on orthogonal projections and others.
  core/math/projection.cpp
  tests/core/math/test_projection.h
  tests/test_main.cpp
Labels: bug, topic:core

#778 [4.3] Enable `ColorPicker` RGB+RAW modes to have overbright values
  scene/gui/color_mode.h
  scene/gui/color_picker.cpp
Labels: enhancement, topic:gui, cherrypick:master

#776 [4.3] Fix `EditorSpinSlider` grabber doesn't follow parent when scrolling
  editor/gui/editor_spin_slider.cpp
Labels: bug, topic:editor, topic:gui, cherrypick:master

#777 [4.3] Fix `ScrollBar` grabber mouse ignores scroll margin
  scene/gui/scroll_bar.cpp
Labels: bug, topic:editor, topic:gui, cherrypick:master

#805 [4.3] Fix `CanvasItemEditor` redraw on key echo
  editor/plugins/canvas_item_editor_plugin.cpp
Labels: bug, topic:editor, topic:2d, cherrypick:master

#806 [4.3] Unify `CanvasItemEditor` duplicate hovering behavior
  editor/plugins/canvas_item_editor_plugin.cpp
  editor/plugins/canvas_item_editor_plugin.h
Labels: enhancement, topic:editor, topic:2d, cherrypick:master

#807 [4.3] Overhaul `CanvasItemEditor` snap lines drawing and input
  editor/plugins/canvas_item_editor_plugin.cpp
  editor/plugins/canvas_item_editor_plugin.h
Labels: bug, topic:editor, topic:2d, cherrypick:master

#812 [4.3] Fix Linux desktop files
  misc/dist/linux/org.redotengine.Redot.appdata.xml
  misc/dist/linux/org.redotengine.Redot.desktop
  misc/dist/linux/org.redotengine.Redot.xml
  platform/linuxbsd/wayland/display_server_wayland.cpp
Labels: rebranding, platform:linuxbsd

#811 [4.3] Fix standard Godot theme missing in preset list
  editor/editor_settings.cpp
Labels: bug, topic:editor, topic:gui

#815 Fix `GDExtensionAPIDump` lacking status_version header
  core/extension/extension_api_dump.cpp
Labels: bug, rebranding, topic:gdextension, cherrypick:4.3

#810 Add `wheel_picker_cursor` theme icon to `ColorPicker`
  doc/classes/ColorPicker.xml
  editor/icons/WheelPickerCursor.svg
  editor/themes/editor_theme_manager.cpp
  scene/gui/color_picker.cpp
  scene/gui/color_picker.h
  scene/theme/default_theme.cpp
  scene/theme/icons/color_picker_wheel_cursor.svg
Labels: enhancement, topic:gui

#816 [4.3] Fix `GDExtensionAPIDump` lacking status_version header
  core/extension/extension_api_dump.cpp
Labels: bug, rebranding, topic:gdextension

#819 [4.3] Fix Godot Reference for update URL
  editor/engine_update_label.cpp
Labels: bug, rebranding, topic:editor, topic:network, cherrypick:master

#825 Fix Snap icon removal introduced in e8e8a88
  editor/icons/Snap.svg
Labels: bug, topic:editor, cherrypick:4.3

#824 Fix Godot headers for AHashMap to Redot
  core/templates/a_hash_map.cpp
  core/templates/a_hash_map.h
  tests/core/templates/test_a_hash_map.h
Labels: rebranding

#829 [4.3] Fix Kotlin license headers referring to Godot
  platform/android/java/editor/src/main/java/org/godotengine/editor/EditorWindowInfo.kt
  platform/android/java/editor/src/main/java/org/godotengine/editor/GodotEditor.kt
  platform/android/java/editor/src/main/java/org/godotengine/editor/GodotGame.kt
  platform/android/java/lib/src/org/godotengine/godot/Godot.kt
  platform/android/java/lib/src/org/godotengine/godot/GodotActivity.kt
  platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt
  platform/android/java/lib/src/org/godotengine/godot/io/StorageScope.kt
  platform/android/java/lib/src/org/godotengine/godot/io/directory/AssetsDirectoryAccess.kt
  platform/android/java/lib/src/org/godotengine/godot/io/directory/DirectoryAccessHandler.kt
  platform/android/java/lib/src/org/godotengine/godot/io/directory/FilesystemDirectoryAccess.kt
  platform/android/java/lib/src/org/godotengine/godot/io/file/DataAccess.kt
  platform/android/java/lib/src/org/godotengine/godot/io/file/FileAccessFlags.kt
  platform/android/java/lib/src/org/godotengine/godot/io/file/FileAccessHandler.kt
  platform/android/java/lib/src/org/godotengine/godot/io/file/FileData.kt
  platform/android/java/lib/src/org/godotengine/godot/io/file/FileErrors.kt
  platform/android/java/lib/src/org/godotengine/godot/io/file/MediaStoreData.kt
  platform/android/java/lib/src/org/godotengine/godot/utils/BenchmarkUtils.kt
  platform/android/java/lib/src/org/godotengine/godot/utils/CommandLineFileParser.kt
  platform/android/java/lib/src/org/godotengine/godot/vulkan/VkRenderer.kt
  platform/android/java/lib/src/org/godotengine/godot/vulkan/VkSurfaceView.kt
  platform/android/java/lib/src/org/godotengine/godot/vulkan/VkThread.kt
  platform/android/java/lib/srcTest/java/org/godotengine/godot/utils/CommandLineFileParserTest.kt
Labels: cherrypick:master

#826 Add rotation to the `ColorPicker.wheel_picker_cursor` icon
  doc/classes/ColorPicker.xml
  scene/gui/color_picker.cpp
Labels: enhancement, topic:gui

#830 [4.3] Fix remainder of godotengine references
  editor/doc_tools.cpp
  editor/editor_help.cpp
  editor/editor_node.cpp
  editor/editor_property_name_processor.cpp
  editor/fbx_importer_manager.cpp
  platform/linuxbsd/wayland/display_server_wayland.cpp
Labels: bug, rebranding, cherrypick:master
