Repository Redot-Engine/redot-engine, pull requests merged in 2025-03, with the labels that each got.

#977 [4.3] Fix Tilemap release display bug
  editor/editor_file_system.cpp
  editor/editor_file_system.h
  editor/editor_log.cpp
  editor/editor_node.cpp
  modules/gltf/editor/editor_scene_importer_blend.cpp
  scene/2d/tile_map.cpp
  scene/gui/rich_text_label.cpp
  scene/gui/rich_text_label.h
Labels: bug, regression, topic:2d

#978 [4.3] Fixed occlusion culling buffer getting overwritten in larger scenes
  modules/raycast/raycast_occlusion_cull.cpp
Labels: bug, topic:rendering, regression

#980 [4.3] Bump to 4.3.1 beta
  version.py
Labels: enhancement

#981 [4.3] CI: Add redot-cpp testing
  .github/workflows/redot_cpp_test.yml
  .github/workflows/runner.yml
Labels: enhancement, topic:buildsystem, topic:gdextension

#982 CI: Add redot-cpp testing action
  .github/actions/redot-cpp-build/action.yml
  .github/workflows/linux_builds.yml
Labels: enhancement, topic:buildsystem, topic:gdextension
