Repository Redot-Engine/redot-engine, pull requests merged in 2025-08, with the labels that each got.

#1058 Add release changelog builder
  .github/workflows/changelog_builder.yml
Labels: enhancement, topic:buildsystem, cherrypick:4.3, cherrypick:4.4

#1059 [4.4] Add release changelog builder
  .github/workflows/changelog_builder.yml
Labels: enhancement, topic:buildsystem

#1065 Fix changelog builder tag resolver and title transformers
  .github/workflows/changelog_builder.yml
Labels: bug, topic:buildsystem, cherrypick:4.3, cherrypick:4.4

#1066 [4.3] Fix changelog builder tag resolver and title transformers
  .github/workflows/changelog_builder.yml
Labels: bug, topic:buildsystem

#1068 Add user reference to PR template in changelog builder
  .github/workflows/changelog_builder.yml
Labels: enhancement, topic:buildsystem

#1069 [4.3] Add user reference to PR template in changelog builder
  .github/workflows/changelog_builder.yml
Labels: enhancement, topic:buildsystem

#1072 Add Godot drop-in replacement for GDExtension version checks
  core/extension/gdextension_library_loader.cpp
Labels: bug, enhancement, rebranding, topic:gdextension, regression

#1073 [4.4] Add Godot drop-in replacement for GDExtension version checks
  core/extension/gdextension_library_loader.cpp
Labels: bug, enhancement, rebranding, topic:gdextension, regression

#1076 Fix erroneous macOS build bundle generation
  platform/macos/platform_macos_builders.py
Labels: bug, rebranding, platform:macos, topic:buildsystem, regression, cherrypick:4.3, cherrypick:4.4

#1077 [4.3] Fix erroneous macOS build bundle generation
  platform/macos/SCsub
Labels: bug, rebranding, platform:macos, topic:buildsystem, regression

#1079 [4.4] Cherry Pick: Fix animation track inserted path and key type
  editor/animation_track_editor.cpp
Labels: bug, topic:editor, topic:animation

#1089 Fix project manager title showing as (DEBUG)
  scene/main/window.cpp
Labels: bug, topic:editor, topic:gui, 4.3
